// Optional end-to-end check. Requires Playwright and an installed Edge browser.
// Run against a dedicated test server, not an active measurement session.
const {chromium}=require(process.env.GW_PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const url=process.env.GW_TEST_URL || 'http://127.0.0.1:8765';
const output=path.resolve('artifacts/web-check');
(async()=>{
 fs.mkdirSync(output,{recursive:true});
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try {
  const page=await browser.newPage({viewport:{width:1360,height:1040},colorScheme:'light'});
  const errors=[],external=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{if(!request.url().startsWith(url)&&!request.url().startsWith('data:'))external.push(request.url());});
  await page.goto(url);
  await page.locator('[data-signal="S3"]').waitFor();
  await page.waitForFunction(()=>typeof mapData!=='undefined'&&mapData!==null&&hitPoints.length===5);
  await page.getByRole('button',{name:'Nowa sesja / reset'}).click();
  await page.waitForFunction(()=>state.model_version===0&&!busy);
  assert.equal(await page.locator('#target-value').textContent(),'50');
  assert.equal(await page.locator('#follow').isChecked(),true);
  assert.equal((await page.evaluate(()=>state.trajectory.legs)).length,5);
  assert.equal(await page.locator('.badge').textContent(),'LABORATORIUM M4');
  await page.locator('[data-signal="S3"]').click();
  await page.locator('#green').click();
  await page.waitForFunction(()=>state.model_version===1&&!busy);
  let snapshot=await page.evaluate(()=>state);
  assert.deepEqual(snapshot.last_change.signal_ids,['S3']);
  assert.equal(snapshot.signals[2].offset,0);
  assert.equal(snapshot.signals[3].offset,90);
  await page.locator('#rate').selectOption('10');
  await page.getByRole('button',{name:'Start',exact:true}).click();
  await page.waitForFunction(()=>state.position.road_position_m>20);
  await page.getByRole('button',{name:'Pauza',exact:true}).click();
  await page.waitForFunction(()=>!busy&&!state.running);
  const stopped=await page.evaluate(()=>state.simulation_seconds);
  await page.locator('[data-signal="S1"]').click();
  await page.locator('#green').click();
  await page.waitForFunction(()=>state.model_version===2&&!busy);
  snapshot=await page.evaluate(()=>state);
  assert.equal(snapshot.last_change.signal_ids.length,5);
  assert.equal(snapshot.simulation_seconds,stopped);
  await page.locator('#kind').selectOption('STATE_SEEN');
  await page.locator('#red').click();
  await page.waitForFunction(()=>state.model_version===3&&!busy);
  assert.equal((await page.evaluate(()=>state.signals[0].windows)).length,0);
  assert.equal(await page.locator('#target-value').textContent(),'—');
  await page.locator('#kind').selectOption('STATE_START');
  await page.locator('#green').click();
  await page.waitForFunction(()=>state.model_version===4&&!busy);
  await page.locator('#debug summary').click();
  await page.locator('#history summary').click();
  await page.locator('#solver-debug summary').click();
  await page.locator('#debug-rows tr').first().waitFor();
  await page.locator('#trajectory-legs tr').first().waitFor();
  assert.ok((await page.locator('#trajectory-cost').textContent()).includes('Koszt'));
  assert.ok((await page.locator('#trajectory-baseline').textContent()).includes('lokalny'));
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
  await page.emulateMedia({colorScheme:'dark'});
  await page.screenshot({path:path.join(output,'dark.png'),fullPage:true});
  await page.emulateMedia({colorScheme:'light'});
  await page.setViewportSize({width:390,height:1000});
  await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
  const layout=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
  assert.ok(layout.scroll<=layout.width,JSON.stringify(layout));
  await page.locator('#dataset').selectOption('zwirki_wigury');
  await page.waitForFunction(()=>state.dataset==='zwirki_wigury'&&!busy);
  assert.equal(await page.locator('#play').isDisabled(),true);
  await page.locator('#green').click();
  await page.waitForFunction(()=>state.model_version===1&&!busy);
  snapshot=await page.evaluate(()=>state);
  assert.equal(snapshot.signals[0].state,'UNKNOWN');
  assert.equal(snapshot.signals[0].windows.length,0);
  assert.equal(snapshot.timebase,'UTC_ELAPSED');
  assert.ok(snapshot.history_total>=5);
  assert.equal(await page.evaluate(()=>hitPoints.length),0);
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  console.log(JSON.stringify({result:'PASS',errors,external,layout,screenshots:output}));
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
